apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: janus-argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: janus
  source:
    path: k8/service-mesh/istio
    repoURL: https://github.com/redhat-na-ssa/ocp-virt-ossm-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}